config/routes.rb
Rails.application.routes.draw do
  root to: "home#top"
  get 'home/top'
  resources :home do
    collection do
      get :search #ransack検索用
    end

  end
  devise_for :users
  resources :users do
  collection do
      get :user_to_all_rooms
      get :search #ransack検索用
    end
  end

  resources :application do
  end

  resources :rooms do
    collection do
      get :registered_rooms
      get 'search'#ransack検索用
    end

  end

  resources :reservations do
    collection do
      get :reserved_rooms
    end
    member do
      post :confirm
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_q, only: [:index, :search]
  def top
    @user = current_user
    @all_rooms = Room.all
    @q = Room.ransack(params[:q])
  end

  def index
    @user = current_user
    @all_rooms = Room.all
    @q = Room.ransack(params[:q])
    @results = @q.result
    # @room = Room.find(params[:id])
  end


  def show
    @user = current_user
    @q = Room.ransack(params[:q])
    @results = @q.result
    @room = Room.find(params[:id])
    @reservation = Reservation.new #(room_params)いる？
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
  end

  def destroy
  end

  def search
    @results = @q.result #ransack用
    @user = current_user
  end


  private
#ransackはapplicationコントローラに記述
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h3 class="result">検索結果：<%= @results.count(:id) %>件</h3>
<div class="outer_box">
  <% @results.each do |r| %>
  <%= link_to  home_path(r.id) do %><!-- home#showアクションへ -->
      <div class="sample_box">
        <% if r.room_image.attached? %>
            <%= image_tag r.room_image , class:"index_room_image"%>
        <% end %>
        <li class="room_name">
          <%= r.room_name %>
        </li>
        <li class="address">
          <%= r.adress %>
        </li>
        <li class="charge">
          ¥<%= r.charge %>
        </li>
        <li class="ID">
          [roomID]<%= r.id %>
        </li>
      </div>
  <% end %>
<% end %>
    </div>

app/views/home/search.html.erb
<h3>検索結果：<%= @results.count(:id) %>件</h3>
<table>
  <thead>
    <tr>
      <th>id</th>
      <th>ルーム画像</th>
      <th>ルームネーム</th>
      <th>場所</th>
      <th>ルーム紹介</th>
      <th>施設詳細</th>
      <th>料金</th>
      <th>登録者ID</th>
      <th>予約</th>
      <th>削除</th>
    </tr>
  </thead>

  <tbody>
    <% @results.each do |r| %>
      <tr>
        <td>
          <%= r.id %>
        </td>
        <td>
          <% if r.avatar? %>
            <%= image_tag r.avatar.url,class: "room_image" %>
          <% else %>
        <image src="/assets/default_room_image" class="room_image" alt="ユーザーアイコン"><!-- デフォルト画像表示用 -->
          <% end %>
        </td>
        <td>
          <%= r.room_name %>
        </td>
        <td>
          <%= r.address %>
        </td>
        <td>
          <%= r.room_introduction %>
        </td>
        <td>
          <%= link_to "ルーム詳細" , room_path(r) %>
        </td>
        <td>
          <%= r.charge %>円/日
        </td>
        <td>
          <%= r.user_id %>
        </td>
        <td>
          <%= link_to "予約する" , room_path(r) %>
        </td>
        <td>
          <%= link_to "削除" , r, method: :delete, data: { confirm: "本当に削除しますか？" } %>
        </td>
      </tr>
      <% end %>
  </tbody>
</table>

app/views/home/show.html.erb
<div class="box">
  <div class="box-inner">
    <h3 style="text-align: center;">rooms予約フォーム</h3>
    <% if @room.room_image.attached? %>
      <div class="room_image">
        <%= image_tag @room.room_image , class:"edit_room_image"%>
      </div>
      <% end %>
        <table>
          <tr>
            <th>ルーム名</th>
            <td>
              <%= @room.room_name%>
            </td>
          </tr>
          <tr>
            <th>住所</th>
            <td>
              <%= @room.adress %>
            </td>
          </tr>
          <tr>
            <th>値段</th>
            <td>
              <%= @room.charge %>/日
            </td>
          </tr>
          <tr>
            <th>ルーム紹介</th>
            <td>
              <div class="edit-room-introduction">
                <%= @room.room_introduction %>
              </div>
            </td>
          </tr>

    <%= form_with url: confirm_reservation_path, local: true do |f| %>
            <tr>
              <th>
                <%= f.label :start_date ,"開始日" %>
              </th>
              <td>
                <div class="box-email">
                  <%= f.date_field :start_date %>
                </div>
              </td>
            </tr>
            <tr>
              <th>
                <%= f.label :end_date ,"終了日" %>
              </th>
              <td>
                <div class="box-email">
                  <%= f.date_field :end_date %>
                </div>
              </td>
            </tr>
            <tr>
              <th>
                <%= f.label :people ,"人数" %>
              </th>
              <td>
                <div class="box-email">
                  <%= f.number_field :people %>
                </div>
              </td>
            </tr>
        </table>
        <p>
        <div class="box-login">
          <%= f.submit "確認画面へ!" %>
        </div>
        </p>
  </div>
    <%= f.hidden_field :room_name, :value=> @room.room_name %>
    <%= f.hidden_field :charge, :value=> @room.charge %>
    <%= f.hidden_field :room_image, :value=> @room.room_image %>
  <% end %>

    <p style="text-align: center;">
      <%= link_to "Top" , "/" %>
    </p>
</div>
</div>

app/views/home/top.html.erb
<body>
<div class="main top-main">
  <div class="top-message">
    <h2>まだ体験したことのない旅をしよう</h2>
  </div>
</div>


<div class="over_city_container">
    <h1 class="osusume_area">おすすめエリア</h1>
  <div class="outer_city_container" >
    <%= link_to search_home_index_path(q: {address_cont: "東京" }) do %>
    <div class="city_container_tokyo">
      <span>東京</span>
    </div>
    <% end %>

    <%= link_to search_home_index_path(q: {address_cont: "京都" }) do %>
    <div class="city_container_kyoto">
      <span>京都</span>
    </div>
    <% end %>

    <%= link_to search_home_index_path(q: {address_cont: "大阪" }) do %>
    <div class="city_container_osaka">
      <span>大阪</span>
    </div>
    <% end %>

    <%= link_to search_home_index_path(q: {address_cont: "札幌" }) do %>
    <div class="city_container_sapporo">
      <span>札幌</span>
    </div>
    <% end %>
  </div>
</div>
<br>
<div class="all_search_box">
  <%= search_form_for @q, url: search_home_index_path do |f| %>
    <div class="search-outer-box">
      <%= f.search_field :address_cont, class: "search-box" , placeholder:"場所検索  （例）東京" %>
      <%= f.search_field :room_name_or_room_introduction_cont, class: "search-box" , placeholder:"ルームネーム・ルーム紹介" %>
        <%= f.submit "検索" , class: "search-submit" %>
    </div>
    <% end %>
      </body>
</body>

app/views/home/update.html.erb
<div class="box">
  <div class="box-inner">
    <h2>プロフィールを作成</h2>
    <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
      <%= render "devise/shared/error_messages" , resource: resource %>
        <div class="field">
          <div class="box-username">
            <%= f.label :username, "ユーザーネーム" %><br />
              <%= f.text_field :username, class: "form-control" %>
          </div>
        </div>

        <div class="field">
          <div class="box-email">
            <%= f.label :email,"Eメール" %><br />
              <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
          </div>
        </div>

        <div class="field">
          <div class="box-password">
            <%= f.label :password, "パスワード" %>
              <% if @minimum_password_length %>
                <em>(<%= @minimum_password_length %> 文字以上)</em>
                <% end %><br />
                  <%= f.password_field :password, autocomplete: "new-password" %>
          </div>
        </div>

        <div class="field">
          <div class="box-password">
            <%= f.label :password_confirmation, "パスワード確認" %><br />
              <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
          </div>
        </div>

        <div class="actions">
          <div class="box-login">
            <%= f.submit "新しいアカウントを作成" %>
          </div>
        </div>
        <% end %>
          <div class="mklg">
            <%= render "devise/shared/links" %>
          </div>
  </div>
</div>